routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('frontend.home.index');
});*/
Route::get('/', 'Frontend\MainController@index');



Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['admin']], function(){
    Route::prefix('admin/')->group(function (){
        Route::get('dashboard', 'Backend\AdminController@index')->name('dashboard');
        Route::resource('users', 'Backend\UserController');
        Route::resource('categories', 'Backend\CategoryController');
        Route::resource('slogans', 'Backend\SloganController');
        Route::resource('welcomes', 'Backend\WelcomeController');
        Route::resource('posts', 'Backend\PostController');
        Route::resource('sliders', 'Backend\SliderController');
        Route::resource('abouts', 'Backend\AboutController');
        Route::resource('photos', 'Backend\PhotoController');
        Route::resource('news', 'Backend\NewsController');
        Route::resource('products', 'Backend\ProductController');
        Route::resource('certificates', 'Backend\CertificateController');
        Route::resource('responses', 'Backend\ResponseController');
        Route::resource('galleries', 'Backend\GalleryController');

       // Route::get('requisitions/edited/{id}', 'Backend\RequisitionController@edited')->name('response.edit');
       // Route::delete ('requisitions/delete/{id}', 'Backend\RequisitionController@destroy')->name('response.delete');
        //Route::get('requisitions', 'Backend\RequisitionController@index');

        Route::post('photos/upload', 'Backend\PhotoController@upload')->name('photos.upload');
        Route::post('galleries/upload', 'Backend\GalleryController@upload')->name('galleries.upload');
        Route::post('sliders/slideUpload','Backend\SliderController@slideUpload')->name('sliders.slideUpload');
        Route::post('welcomes/welcomeUpload', 'Backend\WelcomeController@welcomeUpload')->name('welcomes.Upload');
        Route::post('news/upload', 'Backend\NewsController@upload')->name('news.upload');
        Route::post('products/upload', 'Backend\ProductController@upload')->name('products.upload');
        Route::post('certificates/upload', 'Backend\CertificateController@upload')->name('certificates.upload');

    });
});


Route::get('category/{id}', 'Frontend\MainController@getPostByCategory')->name('category.index');
Route::resource('frontend/requisitions', 'Frontend\RequisitionController');
Route::get('frontend/about', 'Frontend\AboutController@index')->name('about');
Route::get('frontend/contact', 'Frontend\ContactController@index')->name('contact');
Route::get('frontend/gallery', 'Frontend\GalleryController@index')->name('gallery');
Route::get('frontend/services', 'Frontend\ServiceController@index')->name('services');
Route::get('frontend/posts/{id}', 'Frontend\MainController@getPostContent')->name('post');
Route::get('frontend/news/{id}', 'Frontend\MainController@getNewsContent')->name('news');
Route::get('frontend/products/{id}', 'Frontend\MainController@getProductContent')->name('product');




Auth::routes();

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
    //
}

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.abouts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/AboutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\About;
use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    public function index()
    {

        $about=About::where('status',1)->first();
        return view('frontend.about.index',compact(['about']));
    }
}

resources/views/admin/abouts/create.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="content">
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box-header with-border mt-3 mr-2 ml-2">
                @if($errors->any())
                    <ul>
                        <div class="alert alert-danger">
                            @foreach($errors->all() as $error)
                                <li >{{$error}}</li>
                            @endforeach
                        </div>
                    </ul>
                @endif
                <div class="col-lg-12">
                    <div class="card ">
                        <h3 class="box-title pull-right mr-2 mt-2">گروه ها</h3>
                        <div class="text-left">
                            <a class="btn btn-app" href="{{route('slogans.create')}}">
                                <i class="fa fa-plus green"></i> جدید
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card ">
                                <div class="card-body offset-md-2 col-md-6 ">
                                    <form method="post" action="/admin/slogans">
                                        @csrf
                                        <div class="form-group">
                                            <label for="title">نام</label>
                                            <textarea type="text" name="title" class="form-control @error('title') is-invalid @enderror"
                                                      placeholder="شعار سایت را وارد کنید..."></textarea>
                                        </div>
                                        <label>وضعیت انتشار </label>
                                        <br/>
                                        <input type="checkbox" name="status"  data-toggle="toggle" class="form-control ">
                                        <br/>
                                        <button type="submit" class="btn btn-success pull-left">ذخیره</button>
                                    </form>
                                </div>

                            </div>
                        </div>
                        <!-- /.col-md-6 -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
    </section>


@endsection

resources/views/admin/abouts/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <section class="content">
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box-header with-border mt-3 mr-2 ml-2">
                @if($errors->any())
                    <ul>
                        <div class="alert alert-danger">
                            @foreach($errors->all() as $error)
                                <li >{{$error}}</li>
                            @endforeach
                        </div>
                    </ul>
                @endif
                <div class="col-lg-12">
                    <div class="card ">
                        <h3 class="box-title pull-right mr-2 mt-2">شعار ها</h3>

                    </div>
                </div>
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card ">
                                <div class="card-body offset-md-2 col-md-6 ">
                                    <form method="post" action="/admin/slogans/{{$slogan->id}}">
                                        @csrf
                                        <input type="hidden" name="_method" value="PATCH">
                                        <div class="form-group">
                                            <label for="title">نام</label>
                                            <input type="text" name="title"  value="{{$slogan->title}}" class="form-control @error('title') is-invalid @enderror"
                                                   placeholder="عنوان شعار را وارد کنید...">
                                        </div>
                                        <label>وضعیت انتشار
                                            <br>
                                            <input type="checkbox" name="status" @if($slogan->status==1) checked @endif data-toggle="toggle" class="form-control">
                                        </label>

                                        <button type="submit" class="btn btn-success pull-left">ذخیره</button>
                                    </form>
                                </div>

                            </div>
                        </div>
                        <!-- /.col-md-6 -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
    </section>


@endsection

resources/views/admin/abouts/index.blade.php
@extends('admin.layouts.master')
@section('style')

@endsection
@section('content')

    <section class="content">
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="box-header with-border mt-3 mr-2 ml-2">
                <div class="col-lg-12">
                    <div class="card ">
                        <h3 class="box-title pull-right mr-2 mt-2">در باره ما</h3>
                        <div class="text-left">
                            <a class="btn btn-app" href="{{route('abouts.create')}}">
                                <i class="fa fa-plus green"></i> جدید
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card ">
                                <div class="card-body offset-md-0 ">
                                    <h3> درباره ما</h3>
                                    <div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.col-md-6 -->
                    </div>
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
    </section>

@endsection

@section('script')
    <script type="text/javascript" src="{{asset('admin/plugins/ckeditor/ckeditor.js')}}"></script>
@endsection
<script>
    CKEDITOR.replace('Description',{
        customConfig: 'config.js',
        toolbar: 'simple',
        language: 'fa',
       // removePlugins: 'cloudservices, easyimage'
    })
</script>