routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('frontend.home.index');
});*/
Route::get('/', 'Frontend\MainController@index');



Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['admin']], function(){
    Route::prefix('admin/')->group(function (){
        Route::get('dashboard', 'Backend\AdminController@index')->name('dashboard');
        Route::resource('users', 'Backend\UserController');
        Route::resource('categories', 'Backend\CategoryController');
        Route::resource('slogans', 'Backend\SloganController');
        Route::resource('welcomes', 'Backend\WelcomeController');
        Route::resource('posts', 'Backend\PostController');
        Route::resource('sliders', 'Backend\SliderController');
        Route::resource('abouts', 'Backend\AboutController');
        Route::resource('photos', 'Backend\PhotoController');
        Route::resource('news', 'Backend\NewsController');
        Route::resource('products', 'Backend\ProductController');
        Route::resource('certificates', 'Backend\CertificateController');
        Route::resource('responses', 'Backend\ResponseController');
        Route::resource('galleries', 'Backend\GalleryController');

       // Route::get('requisitions/edited/{id}', 'Backend\RequisitionController@edited')->name('response.edit');
       // Route::delete ('requisitions/delete/{id}', 'Backend\RequisitionController@destroy')->name('response.delete');
        //Route::get('requisitions', 'Backend\RequisitionController@index');

        Route::post('photos/upload', 'Backend\PhotoController@upload')->name('photos.upload');
        Route::post('galleries/upload', 'Backend\GalleryController@upload')->name('galleries.upload');
        Route::post('sliders/slideUpload','Backend\SliderController@slideUpload')->name('sliders.slideUpload');
        Route::post('welcomes/welcomeUpload', 'Backend\WelcomeController@welcomeUpload')->name('welcomes.Upload');
        Route::post('news/upload', 'Backend\NewsController@upload')->name('news.upload');
        Route::post('products/upload', 'Backend\ProductController@upload')->name('products.upload');
        Route::post('certificates/upload', 'Backend\CertificateController@upload')->name('certificates.upload');

    });
});


Route::get('category/{id}', 'Frontend\MainController@getPostByCategory')->name('category.index');
Route::resource('frontend/requisitions', 'Frontend\RequisitionController');
Route::get('frontend/about', 'Frontend\AboutController@index')->name('about');
Route::get('frontend/contact', 'Frontend\ContactController@index')->name('contact');
Route::get('frontend/gallery', 'Frontend\GalleryController@index')->name('gallery');
Route::get('frontend/services', 'Frontend\ServiceController@index')->name('services');
Route::get('frontend/posts/{id}', 'Frontend\MainController@getPostContent')->name('post');
Route::get('frontend/news/{id}', 'Frontend\MainController@getNewsContent')->name('news');
Route::get('frontend/products/{id}', 'Frontend\MainController@getProductContent')->name('product');




Auth::routes();

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $uploads = '/storage/photos/';

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getPathAttribute($photo)
    {
        return $this->uploads . $photo;
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function welcomes()
    {
        return $this->hasMany(Welcome::class);
    }

    public function news()
    {
        return $this->hasMany(News::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function certificates()
    {
        return $this->hasMany(Certificate::class);
    }

    public function galleries()
    {
        return $this->hasMany(Gallery::class);
    }
}

app/Http/Controllers/Frontend/AboutController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\About;
use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    public function index()
    {

        $about=About::where('status',1)->first();
        return view('frontend.about.index',compact(['about']));
    }
}

app/Http/Controllers/Frontend/ContactController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    public function index()
    {

        return view('frontend.contact.index');
   }
}

app/Http/Controllers/Frontend/GalleryController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Category;
use App\Gallery;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    public function index()
    {
        $galleries=Gallery::with('photo')->get();
        return view('frontend.gallery.index',compact('galleries'));
    }
}

app/Http/Controllers/Frontend/MainController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Category;
use App\Certificate;
use App\Http\Controllers\Controller;
use App\News;
use App\Post;
use App\Product;
use App\Slider;
use App\Slogan;
use App\Welcome;
use App\User;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index()
    {

        $welcomes = Welcome::where('status',1)->orderBy('status','DESC')->orderBy('created_at','DESC')->get();
        $certificate =Certificate::with('photo')->
        where('status',1)->
        orderByDesc('created_at')->
        first();
        $products = Product::where('status',1)
            ->orderBy('status','DESC')
            ->orderBy('created_at','DESC')
            ->paginate(10);


        $news=News::with('photo')->
        where('status',1)->
        where('first_page',1)->
        orderByDesc('created_at')->
        limit(10)->
        get();

        $posts=Post::with('photo')->
                     where('status',1)->
                     where('first_page',1)->
                     orderByDesc('created_at')->
                     limit(3)->
                      get();
        $sliders=Slider::all();
        $slogan = Slogan::where('status',1)->
        orderByDesc('created_at')->
        first();
        /*$categories = Category::whereNull('category_id')
            ->with('childrenCategories')
            ->where('status',1)
            ->get();*/
        return view('frontend.home.index',compact(['slogan','posts','sliders','welcomes','news','products','certificate']));
    }
    public function getPostByCategory($id)
    {
        $categories = Category::whereNull('category_id')
            ->with('childrenCategories')
            ->where('status',1)
            ->get();
        $category = Category::whereId($id)->first();
        $cate = Category::where('category_id',$id)->get();
        $posts=Post::with('category','photo')
            ->where('category_id',$category->id)
            ->where('status',1)
            ->get();
        return view('frontend.categories.index', compact([ 'posts','categories','category','cate']));
    }

    public function getPostContent($id)
    {
       $post=Post::with('photo')
            ->where('id',$id)
            ->where('status',1)
            ->first();
        return view('frontend.posts.index', compact([ 'post']));
    }

    public function getNewsContent($id)
    {
        $news=News::with('photo')
            ->where('id',$id)
            ->where('status',1)
            ->first();
        return view('frontend.news.index', compact([ 'news']));
    }

    public function getProductContent($id)
    {
        $product = Product::with('photo')
            ->where('status',1)
            ->first();
        return view('frontend.products.index', compact([ 'product']));
    }

}

app/Http/Controllers/Frontend/RequisitionController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Category;
use App\Http\Controllers\Controller;
use App\Requisition;
use Illuminate\Http\Request;

class RequisitionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /*$categories = Category::whereNull('category_id')
            ->with('childrenCategories')
            ->where('status',1)
            ->get();
        return view('frontend.requisitions.index',compact('categories'));*/
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

       return view('frontend.requisitions.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $requisition=new Requisition();
        $requisition->subject=$request->input('subject');
        $requisition->title=$request->input('title');
        $requisition->mobile=$request->input('mobile');
        $requisition->name=$request->input('name');
        $requisition->email=$request->input('email');
        $requisition->status=0;
        $requisition->response=0;

        $requisition->save();
        alert()->success('بدون خطا',' درخواست شما "  '.$requisition->subject .'" با موفقیت ثبت شد ');

        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/ServiceController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    public function index()
    {

        return view('frontend.services.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $categories = Category::whereNull('category_id')
            ->with('childrenCategories')
            ->where('status',1)
            ->get();
        return view('frontend.home.index',compact(['categories']));
    }
}

resources/views/frontend/home/index.blade.php
@extends('frontend.layouts.master')

@section('slogan')
    @if($slogan)
        <div class="banner-center">
            <marquee dir="ltr" direction="right" style="font-family: 'Yekan',sans-serif;">
                <h3 style=" font-family: Yekan ,'Ubuntu Condensed', sans-serif;">{{$slogan->title}}</h3>
            </marquee>
        </div>
    @endif
@endsection
@section('banner')
    <div class="banner" >
        <div  >
            @foreach($sliders as $slider)
                <img class="banner-img mySlides "  width="100%"   src="/storage/photos/{{$slider->path}}" alt="ایران گردو">
            @endforeach
        </div>
        @endsection
        @section('content')
            <div class="content">
                <div class="welcome-section">
                    <div class="container">
                        <div class="banner-bottom">
                            <div class="banner-grids">
                                @php $i=1 @endphp
                                @foreach($posts as $post)
                                    <div
                                        class="col-md-4 banner-grid wow  @if($i==1 ) fadeInRight @elseif ($i==2) fadeInDownBig @else fadeInLeft @endif ">
                                        <h4>{{$post->title}}</h4>
                                        <div class="ban1">
                                            <div class="ban-images  view fourth-effect">
                                                <img src="{{$post->photo->path}}" class="img-responsive" alt=""/>
                                                <div class="mask"></div>
                                            </div>
                                            <p>{{$post->short_description}}</p>
                                            <a href="{{route('post',['id'=>$post->id])}}" class="button hvr-wobble-bottom">اطلاعات بیشتر</a>
                                        </div>
                                    </div>
                                    @php $i++ @endphp
                                @endforeach
                                <div class="clearfix"></div>
                            </div>
                        </div>

                        @if(count($welcomes)!=0)
                            <h2>خوش آمدید</h2>
                            <div class="welcome-grids">
                                @php $i=1 @endphp
                                @foreach($welcomes as $welcome)
                                    <div
                                        class="col-md-3 welcome-grid wow @if($i==1)fadeInRight @elseif($i==2)fadeInDownBig @elseif($i==3) fadeInUpBig @else fadeInLeft @endif  ">
                                        <div class="welcome-text">
                                            <h4>{{$welcome->title}}</h4>
                                            <p style="min-height: 250px">{{$welcome->description}}</p>
                                        </div>
                                        <div class="welcome-icon">
                                            <img src="{{$welcome->photo->path}}">
                                        </div>
                                    </div>
                                    @php $i++ @endphp
                                @endforeach
                                <div class="clearfix"></div>
                            </div>
                        @endif
                    </div>
                </div>
                <!---welcome-->

                <!---product-->
                @if(count($products)!=0)
                    <div class="product-section">
                        <div class="container">
                            <h3>محصولات محبوب</h3>
                            @php $i=0;$flag=true;@endphp
                            @foreach($products as $product)
                                @if($flag==true)
                                    <div class="product-grids">
                                        @if($i==0)
                                            <div class="col-md-6 product-grid wow fadeInRight ">
                                                <div class="product-right">
                                                    <img src="{{$product->photo->path}}" class="img-responsive" alt=""/>
                                                </div>
                                                <div class="product-left" >
                                                    <h4>{{$product->title}}</h4>
                                                    {!! Str::limit($product->detail,40)  !!}
                                                    <a href="{{route('product',['id'=>$product->id])}}"><i class="glyphicon glyphicon-circle-arrow-left"
                                                                                                           aria-hidden="true"></i></a>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                            @php $i=1;@endphp
                                        @else
                                            <div class="col-md-6 product-grid wow fadeInLeft ">
                                                <div class="product-right">
                                                    <img src="{{$product->photo->path}}" class="img-responsive" alt=""/>
                                                </div>
                                                <div class="product-left">
                                                    <h4>{{$product->title}}</h4>
                                                    {!! Str::limit($product->detail,40)  !!}
                                                    <a href="{{route('product',['id'=>$product->id])}}"><i class="glyphicon glyphicon-circle-arrow-left"
                                                                                                           aria-hidden="true"></i></a>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                            <div class="clearfix"></div>
                                            @php $i=0;$flag=false;@endphp
                                        @endif
                                    </div>
                                @else
                                    <div class="product-grids">
                                        @if($i==0)
                                            <div class="col-md-6 product-grid1 wow fadeInRight ">
                                                <div class="product1-right">
                                                    <h4>{{$product->title}}</h4>
                                                    {!! Str::limit($product->detail,40)  !!}
                                                    <a href="{{route('product',['id'=>$product->id])}}"><i class="glyphicon glyphicon-circle-arrow-left"
                                                                              aria-hidden="true"></i></a>
                                                </div>
                                                <div class="product1-left">
                                                    <img src="{{$product->photo->path}}" class="img-responsive" alt=""/>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                            @php $i=1;@endphp
                                        @else
                                            <div class="col-md-6 product-grid1 wow fadeInLeft ">
                                                <div class="product1-right">
                                                    <h4>{{$product->title}}</h4>
                                                    {!! Str::limit($product->detail,40)  !!}
                                                    <a href="{{route('product',['id'=>$product->id])}}"><i class="glyphicon glyphicon-circle-arrow-left"
                                                                              aria-hidden="true"></i></a>
                                                </div>
                                                <div class="product1-left">
                                                    <img src="{{$product->photo->path}}" class="img-responsive" alt=""/>
                                                </div>
                                                <div class="clearfix"></div>
                                            </div>
                                            <div class="clearfix"></div>
                                            @php $i=0;$flag=true; @endphp
                                        @endif
                                    </div>
                                @endif
                            @endforeach


                        </div>
                    </div>
                @endif
            <!---product-->
                @if(count($news)!=0)
                <!---news--->
                    <div class="news-section">
                        <div class="container">
                            <h3>آخرین اخبار</h3>
                            @php $i=1 @endphp
                            @foreach($news as $new)
                                <div class="news-grids wow  @if($i%2==1)fadeInLeft @elseif($i%2==0)fadeInRight @endif  ">
                                    <div class="col-md-4 new-grid">
                                        <div id="box" class="burst-circle teal">
                                            <div class="caption"></div>
                                            <img style="max-height: 250px;" src="{{$new->photo->path }}"
                                                 class="img-responsive"/>
                                            <h4> {{$new->title }} </h4>
                                        </div>
                                    </div>
                                    <div class="col-md-8 new-grid1 hvr-bounce-to-left">
                                        <h5><i class="glyphicon glyphicon-calendar"
                                               aria-hidden="true"></i> {{\Hekmatinasser\Verta\Verta::instance($new->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}</h5>
                                        <a href="{{route('news',['id'=>$new->id])}}"> {{$new->short_description }}</a>
                                        {!! Str::limit($new->long_description,50)  !!}                                </div>
                                    <div class="clearfix"></div>
                                </div>
                            @php $i++ @endphp
                        @endforeach

                        <!---news--->
                        </div>
                    </div>
                    <!---news--->
                @endif
            </div>
        @endsection
        @section('script')
            <script>
                var myIndex = 0;
                carousel();

                function carousel() {
                    var i;
                    var x = document.getElementsByClassName("mySlides");
                    if (x==0)
                        return;
                    for (i = 0; i < x.length; i++) {
                        x[i].style.display = "none";
                    }
                    myIndex++;
                    if (myIndex > x.length) {myIndex = 1}
                    x[myIndex-1].style.display = "block";
                    setTimeout(carousel, 5000); // Change image every 2 seconds
                }
            </script>
@endsection