routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('frontend.home.index');
});*/
Route::get('/', 'Frontend\MainController@index');



Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['admin']], function(){
    Route::prefix('admin/')->group(function (){
        Route::get('dashboard', 'Backend\AdminController@index')->name('dashboard');
        Route::resource('users', 'Backend\UserController');
        Route::resource('categories', 'Backend\CategoryController');
        Route::resource('slogans', 'Backend\SloganController');
        Route::resource('welcomes', 'Backend\WelcomeController');
        Route::resource('posts', 'Backend\PostController');
        Route::resource('sliders', 'Backend\SliderController');
        Route::resource('abouts', 'Backend\AboutController');
        Route::resource('photos', 'Backend\PhotoController');
        Route::resource('news', 'Backend\NewsController');
        Route::resource('products', 'Backend\ProductController');
        Route::resource('certificates', 'Backend\CertificateController');
        Route::resource('responses', 'Backend\ResponseController');
        Route::resource('galleries', 'Backend\GalleryController');

       // Route::get('requisitions/edited/{id}', 'Backend\RequisitionController@edited')->name('response.edit');
       // Route::delete ('requisitions/delete/{id}', 'Backend\RequisitionController@destroy')->name('response.delete');
        //Route::get('requisitions', 'Backend\RequisitionController@index');

        Route::post('photos/upload', 'Backend\PhotoController@upload')->name('photos.upload');
        Route::post('galleries/upload', 'Backend\GalleryController@upload')->name('galleries.upload');
        Route::post('sliders/slideUpload','Backend\SliderController@slideUpload')->name('sliders.slideUpload');
        Route::post('welcomes/welcomeUpload', 'Backend\WelcomeController@welcomeUpload')->name('welcomes.Upload');
        Route::post('news/upload', 'Backend\NewsController@upload')->name('news.upload');
        Route::post('products/upload', 'Backend\ProductController@upload')->name('products.upload');
        Route::post('certificates/upload', 'Backend\CertificateController@upload')->name('certificates.upload');

    });
});


Route::get('category/{id}', 'Frontend\MainController@getPostByCategory')->name('category.index');
Route::resource('frontend/requisitions', 'Frontend\RequisitionController');
Route::get('frontend/about', 'Frontend\AboutController@index')->name('about');
Route::get('frontend/contact', 'Frontend\ContactController@index')->name('contact');
Route::get('frontend/gallery', 'Frontend\GalleryController@index')->name('gallery');
Route::get('frontend/services', 'Frontend\ServiceController@index')->name('services');
Route::get('frontend/posts/{id}', 'Frontend\MainController@getPostContent')->name('post');
Route::get('frontend/news/{id}', 'Frontend\MainController@getNewsContent')->name('news');
Route::get('frontend/products/{id}', 'Frontend\MainController@getProductContent')->name('product');




Auth::routes();

resources/views/admin/partials/category.blade.php
@if(isset($selected_category))
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}" @if($selected_category->category_id == $sub_category->id) selected @endif>{{str_repeat(' --- ', $level)}} {{$sub_category->name}}</option>
        @if(count($sub_category->childrenCategories) > 0)
            @include('admin.partials.category', ['categories' => $sub_category->childrenCategories, 'level' => $level+1, 'selected_category'=>$selected_category])
        @endif
    @endforeach
@else
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}" @if($sub_category->ended==1)style="color: red" @endif>{{str_repeat(' --- ', $level)}} {{$sub_category->name}}</option>
        @if(count($sub_category->childrenCategories) > 0)
            @include('admin.partials.category', ['categories' => $sub_category->childrenCategories, 'level' => $level+1])
        @endif
    @endforeach
@endif

resources/views/admin/partials/category_list.blade.php
@php $i=1 @endphp
@foreach($categories as $sub_category)
    <tr>
        <td class="text-center">{{$sub_category->id}}</td>
        <td >{{str_repeat('---', $level)}} {{$sub_category->name}}</td>
        <td >{{$category->user->name}}</td>
        @if($sub_category->status==1)
            <td class="text-center"><span class="label label-success td-admin">نمایش داده شود</span></td>
        @else
            <td class="text-center"><span class="label label-danger td-admin">نمایش داده نشود</span></td>
        @endif
        @if($sub_category->ended==1)
            <td class="text-center"><span class="label label-success td-admin">پستی ثبت شده</span></td>
        @else
            <td class="text-center"><span class="label label-danger td-admin">پستی ثبت نشده</span></td>
        @endif
        <td class="text-center">
            {{\Hekmatinasser\Verta\Verta::instance($sub_category->created_at)->formatDifference(\Hekmatinasser\Verta\Verta::today('Asia/Tehran'))}}
        </td>
        <td>
            <div class="row">
                <a class="btn-delete blue mt-auto ml-2"
                   onsubmit="return confirm('Do you really want to delete?');"
                   href="{{route('categories.edit', $sub_category->id)}}">
                    <i class="fa fa-edit"></i>
                </a>
                |
                <form method="post" class="mt-sm"
                      action="/admin/categories/{{$sub_category->id}}">
                    @csrf
                    <input type="hidden" name="_method"
                           value="DELETE">
                    <button type="submit" class="btn-delete">
                        <i class="fa fa-trash red"></i>
                    </button>
                </form>
            </div>
        </td>
    </tr>
    @if(count($sub_category->childrenCategories) > 0)
        @include('admin.partials.category_list', ['categories' => $sub_category->childrenCategories, 'level' => $level+1])
    @endif
    @php $i++; @endphp
@endforeach

resources/views/admin/partials/edit_post_category.blade.php
@if(isset($selected_category))
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}" @if($selected_category->id==$sub_category->id) selected @endIf>{{str_repeat(' --- ',$level)}}{{$sub_category->name}}</option>
        @if(count($sub_category->childrenCategories)>0)
            @include('admin.partials.edit_post_category',['categories'=>$sub_category->childrenCategories,'level'=>$level+1,'selected_category'])
        @endif
    @endforeach
@else
    @foreach($categories as $sub_category)
        <option value="{{$sub_category->id}}">{{str_repeat(' --- ',$level)}}{{$sub_category->name}}</option>
        @if(count($sub_category->childrenCategories)>0)
            @include('admin.partials.edit_post_category',['categories'=>$sub_category->childrenCategories,'level'=>$level+1])
        @endif
    @endforeach
@endif